# Generated by Luca Bernini and Daniele Raimondi on 25/02/2024
"""This module provides the classes for creating spur gears and spur gear
systems. The module allows to compute the mesh stiffness of meshing gears and to
assemble them in systems where kinematic and dynamic analysis can be done."""

from logging import getLogger
from progetto_gearbox.interfaces.simulation_interfaces import Model
from progetto_gearbox.utils.angles import wrapToPi
from numpy import pi
import numpy as np
from numpy.typing import NDArray
from scipy.linalg import block_diag
# import numpy.typing as npt
# import matplotlib.pyplot as plt
# import scipy as sc
from bokeh.plotting import figure, figure, output_file
from bokeh.models import ColumnDataSource, GlyphRenderer
 
logger = getLogger(__name__)

class SpurGear(Model):
    
    def set_geometry(self, module: float = 10, teeth_number: int = 20, pressure_angle: float = np.deg2rad(20), thickness: float = 10) -> None:
        logger.debug("Setting gear geometry...")
        assert isinstance(module, float) and module > 0, "SpurGear 'module' must be a positive 'float'"
        assert isinstance(teeth_number, int) and teeth_number > 0, "SpurGear 'teeth_number' must be a positive int"
        assert isinstance(pressure_angle, float) and module > 0, "SpurGear 'pressure_angle' must be a positive 'float'"
        assert isinstance(thickness, float) and thickness > 0, "SpurGear 'module' must be a positive 'float'"
        self.module = module
        self.teeth_number = teeth_number
        self.pressure_angle = pressure_angle
        self.thickness = thickness
        self.get_diameters_and_radiuses()
        self.get_alpha_angles()
    
    def set_material(self, young: float = 200000, poisson: float = 0.3) -> None:
        logger.debug("Setting gear material...")
        assert isinstance(young, float) and young > 0, "SpurGear 'young' must be a positive 'float'"
        assert isinstance(poisson, float) and poisson > 0, "SpurGear 'module' must be a positive 'float'"
        self.young = young
        self.poisson = poisson

    def get_diameters_and_radiuses(self) -> None:
        logger.debug("Setting gear useful diameters and radiuses...")
        pitch_diameter = self.teeth_number * self.module
        self.diameters = {
            "pitch": pitch_diameter,
            "base": pitch_diameter * np.cos(self.pressure_angle),
            "addendum": pitch_diameter + 2 * self.module,
            "dedendum": pitch_diameter - 2 * self.module,
            "root": pitch_diameter - 2.5 * self.module,
        }
        self.root_greater_than_base = self.diameters["root"] > self.diameters["base"]
        self.radiuses = {name: diameter / 2 for name, diameter in self.diameters.items()}
    
    def get_alpha_angles(self) -> None:
        logger.debug("Setting gear alpha angles...")
        alpha2 = (
            pi / (2 * self.teeth_number)
            + np.tan(self.pressure_angle)
            - self.pressure_angle
        )
        if self.root_greater_than_base:
            self.alpha = {
                2: alpha2,
                4: alpha2 - self.compute_psi_angle(self.diameters["root"]),
                5: self.compute_phi_angle(self.diameters["root"]) - alpha2,
            }
            self.angle_at_root = 2 * self.alpha[4]
        else:
            self.alpha = {
                2: alpha2,
                3: np.arcsin(
                    self.radiuses["base"] / self.radiuses["root"] * np.sin(alpha2)
                ),
            }
            self.angle_at_root = 2 * self.alpha[3]
        self.angle_at_base = 2 * alpha2

    def get_state_space(self, inertia_x: float, inertia_y: float, inertia_t: float):
        logger.info("Setting up the state space model...")
        self.state_names = ["x_pos", "x_vel", "y_pos", "y_vel", "t_pos", "t_vel"]
        self.state_uoms = ["m", "m/s", "m", "m/s", "rad", "rad/s"]
        
        self.input_names = ["x_force","y_force","t_torque"]
        self.input_uoms = ["N","N","Nm"]
        self.input_funcs = [None,None,None]

        self.output_names = ["x_pos", "x_vel", "y_pos", "y_vel", "t_pos", "t_vel"]
        self.output_uoms = ["m", "m/s", "m", "m/s", "rad", "rad/s"]

        self.get_matrices_dimensions()

        self.state_transition_matrix = block_diag(*[np.array([[0, 1],[0, 0]])]*3)

        self.input_matrix = block_diag(
            *[np.array([[0],[1 / inertia_x]]),
              np.array([[0],[1 / inertia_y]]),
              np.array([[0],[1 / inertia_t]])])
        
        self.output_matrix = np.eye(self.no, self.ns)
        self.feedthrough_matrix = np.zeros((self.no, self.ni))
        self.check_matrices_dimensions()
        self.initial_conditions = np.full(self.ns,None)

    
    
    def compute_phi_angle(self, diameter: float | NDArray) -> float | NDArray:
        return np.sqrt(diameter**2 / self.diameters["base"] ** 2 - 1)

    def compute_csi_angle(self, diameter: float | NDArray) -> float | NDArray:
        return np.arcsin(
            self.compute_phi_angle(diameter)
            / np.sqrt(1 + self.compute_phi_angle(diameter) ** 2)
        )
    
    def compute_psi_angle(self, diameter: float | NDArray) -> float | NDArray:
        return self.compute_phi_angle(diameter) - self.compute_csi_angle(diameter)

    def get_plot_figure(self, fig: figure | None = None, animation: bool = False) -> figure:
        if not fig:
            if animation:
                output_file(f"plots/gear_{self.name}_plot.html")
            else:
                output_file(f"plots/gear_{self.name}_animation.html")
            fig = figure(match_aspect=True)
        return fig

    def get_engagement_array(self, engaged_teeth: NDArray[np.bool] | None = None):
        if not engaged_teeth:
            engaged_teeth = np.zeros(self.teeth_number,dtype=np.bool)
            engaged_teeth[0] = True
        return engaged_teeth

    def get_teeth_centre_angle(self, gear_angle: float | NDArray = 0) -> NDArray:
        pitch_angle = 2 * pi / self.teeth_number
        pitch_angle_vector = np.arange(self.teeth_number) * pitch_angle
        return wrapToPi(gear_angle + pitch_angle_vector)
    
    def get_teeth_involutes(self, teeth_centre_angle: NDArray, n_points: int = 10) -> dict[str, NDArray]:
        if self.root_greater_than_base:
            diameters = np.linspace(
                self.diameters["root"], self.diameters["addendum"], n_points
            )
        else:
            diameters = np.linspace(
                self.diameters["base"], self.diameters["addendum"], n_points
            )
        diameters = np.tile(diameters, (self.teeth_number,1))
        right_radiuses = diameters / 2
        left_radiuses = np.fliplr(right_radiuses)
        right_angles = self.compute_psi_angle(diameters) - self.angle_at_base / 2
        left_angles = - np.fliplr(right_angles)
        return {"left_radiuses": left_radiuses, "left_angles": wrapToPi(left_angles + teeth_centre_angle), "right_radiuses": right_radiuses, "right_angles": wrapToPi(right_angles + teeth_centre_angle)}
    
    def get_teeth_sides(self, teeth_centre_angle: NDArray):
        return {"left_radiuses": np.tile(self.radiuses["root"],(self.teeth_number,1)), 
                "left_angles": wrapToPi(self.alpha[3] + teeth_centre_angle), 
                "right_radiuses": np.tile(self.radiuses["root"],(self.teeth_number,1)), 
                "right_angles": wrapToPi(-self.alpha[3] + teeth_centre_angle)}

    def get_teeth_tips(self, teeth_centre_angle: NDArray, n_points: int = 5):
        right_angle = self.compute_psi_angle(self.diameters["addendum"]) - self.angle_at_base / 2
        left_angle = - right_angle
        angles = np.linspace(right_angle,left_angle,n_points+1,endpoint=False)[1:]
        angles = np.reshape(angles, (1,-1)) + teeth_centre_angle
        radiuses = np.full((self.teeth_number,n_points),self.radiuses["addendum"])
        return {"radiuses": radiuses, "angles": angles}

    def build_teeth_data(
            self,
            x_pos: float = 0,
            y_pos: float = 0,
            t_pos: float = 0,
            engaged_teeth=None,
            n_points_involutes: int = 10,
            n_points_tips: int = 5,
        ) -> dict[str, list]:

        engaged_teeth = self.get_engagement_array(engaged_teeth=engaged_teeth)

        teeth_centre_angle = np.reshape(self.get_teeth_centre_angle(t_pos), (-1, 1))
        teeth_involutes = self.get_teeth_involutes(teeth_centre_angle=teeth_centre_angle, n_points=n_points_involutes)
        teeth_tips = self.get_teeth_tips(teeth_centre_angle=teeth_centre_angle, n_points=n_points_tips)

        teeth_radiuses = np.hstack([
            teeth_involutes["right_radiuses"],
            teeth_tips["radiuses"],
            teeth_involutes["left_radiuses"],
        ])
        teeth_angles = np.hstack([
            teeth_involutes["right_angles"],
            teeth_tips["angles"],
            teeth_involutes["left_angles"],
        ])

        if not self.root_greater_than_base:
            teeth_sides = self.get_teeth_sides(teeth_centre_angle=teeth_centre_angle)
            teeth_radiuses = np.hstack([teeth_radiuses, teeth_sides["left_radiuses"], teeth_sides["right_radiuses"]])
            teeth_angles = np.hstack([teeth_angles, teeth_sides["left_angles"], teeth_sides["right_angles"]])

        xs = [list(x_pos + teeth_radiuses[i, :] * np.cos(teeth_angles[i, :])) for i in range(self.teeth_number)]
        ys = [list(y_pos + teeth_radiuses[i, :] * np.sin(teeth_angles[i, :])) for i in range(self.teeth_number)]

        return {
            "xs": xs,
            "ys": ys,
            "fill_color": ["lightblue" if engaged_teeth[i] else "lightgray" for i in range(self.teeth_number)],
            "line_color": ["blue" if engaged_teeth[i] else "black" for i in range(self.teeth_number)],
        }

    def teeth_plot(
            self,
            fig: figure,
            x_pos: float = 0,
            y_pos: float = 0,
            t_pos: float = 0,
            engaged_teeth=None,
            n_points_involutes: int = 10,
            n_points_tips: int = 5,
        ) -> tuple[figure, ColumnDataSource, GlyphRenderer]:

        data = self.build_teeth_data(
            x_pos=x_pos, y_pos=y_pos, t_pos=t_pos,
            engaged_teeth=engaged_teeth,
            n_points_involutes=n_points_involutes,
            n_points_tips=n_points_tips,
        )
        source = ColumnDataSource(data=data)
        renderer = fig.patches(
            xs="xs", ys="ys",
            fill_color="fill_color",
            line_color="line_color",
            line_width=1,
            source=source,
        )
        return fig, source, renderer

    def teeth_root_plot(
            self,
            fig: figure,
            x_pos: float = 0,
            y_pos: float = 0,
        ) -> tuple[figure, ColumnDataSource, GlyphRenderer]:

        source = ColumnDataSource(data=dict(
            x=[x_pos],
            y=[y_pos],
            radius=[self.radiuses["root"]],
        ))

        renderer = fig.circle(
            x="x",
            y="y",
            radius="radius",
            source=source,
            line_color="black",
            fill_color="gray",
            line_width=1,
        )

        return fig, source, renderer
    
    def reference_circles_plot(
            self,
            fig: figure,
            x_pos: float = 0,
            y_pos: float = 0,
        ) -> tuple[figure, ColumnDataSource, GlyphRenderer]:

        radii_names = [k for k in self.radiuses.keys() if k != "root"]
        radii_values = [self.radiuses[k] for k in radii_names]

        source = ColumnDataSource(data=dict(
            x=[x_pos] * len(radii_values),
            y=[y_pos] * len(radii_values),
            radius=radii_values,
        ))

        renderer = fig.circle(
            x="x",
            y="y",
            radius="radius",
            source=source,
            line_color="black",
            fill_color=None,
            line_width=0.5,
            line_dash="dashed",
        )

        return fig, source, renderer
    
    def plot(
            self,
            fig: figure,
            state_vector=np.zeros((6,1)),
            engaged_teeth=None,
            n_points_involutes: int = 10,
            n_points_tips: int = 5,
        ) -> tuple[figure, ColumnDataSource, GlyphRenderer]:
        
        x_pos = state_vector[self.state_names.index("x_pos")]
        y_pos = state_vector[self.state_names.index("y_pos")]
        t_pos = state_vector[self.state_names.index("t_pos")]

        fig, teeth_source, teeth_renderer = self.teeth_plot(
            fig=fig,
            x_pos=x_pos,
            y_pos=y_pos,
            t_pos=t_pos,
            engaged_teeth=engaged_teeth,
            n_points_involutes=n_points_involutes,
            n_points_tips=n_points_tips,
        )

        fig, root_source, root_renderer = self.teeth_root_plot(
            fig=fig,
            x_pos=x_pos,
            y_pos=y_pos,
        )

        fig, ref_source, ref_renderer = self.reference_circles_plot(
            fig=fig,
            x_pos=x_pos,
            y_pos=y_pos,
        )

        sources = {
            "teeth": teeth_source,
            "root": root_source,
            "reference_circles": ref_source,
        }

        renderers = {
            "teeth": teeth_renderer,
            "root": root_renderer,
            "reference_circles": ref_renderer,
        }

        return fig, sources, renderers

    def update_teeth_plot(
            self,
            source: ColumnDataSource,
            x_pos: float = 0,
            y_pos: float = 0,
            t_pos: float = 0,
            engaged_teeth=None,
            n_points_involutes: int = 10,
            n_points_tips: int = 5,
        ) -> None:
        
        source.data = self.build_teeth_data(
            x_pos=x_pos, y_pos=y_pos, t_pos=t_pos,
            engaged_teeth=engaged_teeth,
            n_points_involutes=n_points_involutes,
            n_points_tips=n_points_tips,
        )

    def update_teeth_root_plot(
            self,
            source: ColumnDataSource,
            x_pos: float = 0,
            y_pos: float = 0,
        ) -> None:

        source.data = dict(
            x=[x_pos],
            y=[y_pos],
            radius=[self.radiuses["root"]],
        )

    def update_reference_circles_plot(
            self,
            source: ColumnDataSource,
            x_pos: float = 0,
            y_pos: float = 0,
        ) -> None:

        n = len(source.data["radius"])
        source.data = dict(
            x=[x_pos] * n,
            y=[y_pos] * n,
            radius=source.data["radius"],
        )

    def update_plot(
            self,
            sources: dict,
            state_vector: NDArray,
            engaged_teeth: NDArray | None = None,
            n_points_involutes: int = 10,
            n_points_tips: int = 5,
        ) -> None:
        x_pos = state_vector[self.state_names.index("x_pos")]
        y_pos = state_vector[self.state_names.index("y_pos")]
        t_pos = state_vector[self.state_names.index("t_pos")]

        self.update_teeth_plot(
            source=sources["teeth"],
            x_pos=x_pos,
            y_pos=y_pos,
            t_pos=t_pos,
            engaged_teeth=engaged_teeth,
            n_points_involutes=n_points_involutes,
            n_points_tips=n_points_tips,
        )

        self.update_teeth_root_plot(
            source=sources["root"],
            x_pos=x_pos,
            y_pos=y_pos,
        )

        self.update_reference_circles_plot(
            source=sources["reference_circles"],
            x_pos=x_pos,
            y_pos=y_pos,
        )


    


    def set_initial_conditions_from(self, driving_gear: "SpurGear", gamma: float, ii: int = 0, jj: int = 0): 
        theta0 = (
            pi
            - (driving_gear.teeth_number / self.teeth_number)
            * driving_gear.initial_conditions[4]
            + (driving_gear.teeth_number / self.teeth_number + 1) * gamma
            - (pi / 2 / self.teeth_number) * (4 * ii + 4 * jj - 6)
        )
        thetad0 = (
            -driving_gear.initial_conditions[5]
            * driving_gear.teeth_number
            / self.teeth_number
        )
        return theta0, thetad0

    def compute_teeth_engagement(self, teeth_position, mode, gamma, gear_rotation, other_gear): ### fix
        pass
        # csi_a2 = other_gear.compute_csi_angle(other_gear.diameter["addendum"])
        # a0 = self.radius["pitch"] + other_gear.radius["pitch"]
        # ro2 = np.sqrt(
        #     other_gear.radius["addendum"] ** 2
        #     + a0**2
        #     - 2
        #     * other_gear.radius["addendum"]
        #     * a0
        #     * np.cos(csi_a2 - self.pressureAngle)
        # )
        # phi_2 = self.compute_phi_angle(2 * ro2)
        # phi_a = self.compute_phi_angle(self.diameter["addendum"])

        # match (mode, gear_rotation):
        #     case ("driving", gr) if gr > 0:  #
        #         thetagi = wrapToPi(teethPosition - gamma)
        #         theta_start = wrapToPi(
        #             +(-self.pressureAngle + phi_2 - self.angle_at_base / 2)
        #         )
        #         theta_end = wrapToPi(
        #             +(-self.pressureAngle + phi_a - self.angle_at_base / 2)
        #         )
        #     case ("driving", gr) if gr < 0:
        #         thetagi = wrapToPi(teethPosition - gamma)
        #         theta_start = wrapToPi(
        #             -(-self.pressureAngle + phi_2 - self.angle_at_base / 2)
        #         )
        #         theta_end = wrapToPi(
        #             -(-self.pressureAngle + phi_a - self.angle_at_base / 2)
        #         )
        #     case ("driven", gr) if gr > 0:
        #         thetagi = wrapToPi(teethPosition - gamma - pi)
        #         theta_start = wrapToPi(
        #             -(self.pressureAngle - phi_a - self.angle_at_base / 2)
        #         )
        #         theta_end = wrapToPi(
        #             -(self.pressureAngle - phi_2 - self.angle_at_base / 2)
        #         )
        #     case ("driven", gr) if gr < 0:  #
        #         thetagi = wrapToPi(teethPosition - gamma - pi)
        #         theta_start = wrapToPi(
        #             +(self.pressureAngle - phi_a - self.angle_at_base / 2)
        #         )
        #         theta_end = wrapToPi(
        #             +(self.pressureAngle - phi_2 - self.angle_at_base / 2)
        #         )

        # # --- 6) Condizione di ingaggio corretta ---

        # engagement = np.logical_and(thetagi >= theta_start, thetagi < theta_end)

        # if not np.any(engagement):
        #     print("No engagement detected.")

        # # Angolo utile per cinematica
        # alfa1_i = -self.pressureAngle + thetagi

        # return engagement, alfa1_i

    def computeStiffnessAngles(self, t, x): ### fix
        """to be updated"""
        pass

    def meshStiffness(self, engagement, alpha1): ### fix
        # Parameters
        E = self.young
        L = self.thickness
        v = self.poisson

        num_points = 100

        # Define alfa range

        # phig_r - self.angle_at_base/2
        # np.linspace(0, 1, num_points)[None, :] * (stop - start)[:, None] + start[:, None]

        if self.root_greater_than_base:
            # Compute Ib, Is, Ia
            alpha = np.linspace(-alpha1, self.alpha[5], num_points)

            Ib = (
                (
                    3
                    * (
                        1
                        + np.cos(alpha1)
                        * ((self.alpha[2] - alpha) * np.sin(alpha) - np.cos(alpha))
                    )
                    ** 2
                    * (self.alpha[2] - alpha)
                    * np.cos(alpha)
                )
                / (
                    2
                    * E
                    * L
                    * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha)) ** 3
                )
                * engagement
            )
            Is = (
                (
                    1.2
                    * (1 + v)
                    * (self.alpha[2] - alpha)
                    * np.cos(alpha)
                    * np.cos(alpha1) ** 2
                )
                / (E * L * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha)))
                * engagement
            )
            Ia = (
                ((self.alpha[2] - alpha) * np.cos(alpha) * np.sin(alpha1) ** 2)
                / (
                    2
                    * E
                    * L
                    * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha))
                )
                * engagement
            )

        else:
            alpha = np.linspace(-alpha1, self.alpha[2], num_points)

            Ib0 = (
                ## primo termine
                (
                    (
                        1
                        - ((self.teethNumber - 2.5) * np.cos(alpha1) * np.cos(alpha[3]))
                        / (self.teethNumber * np.cos(self.pressureAngle))
                    )
                    ** 3
                    - (1 - np.cos(alpha1) * np.cos(alpha[2] ** 3))
                )
                / (2 * E * L * (np.cos(alpha1) * np.sin(alpha[2]) ** 3))
            )

            ## secondo termine

            Ib = (
                (
                    3
                    * (
                        1
                        + np.cos(alpha1)
                        * ((self.alpha[2] - alpha) * np.sin(alpha) - np.cos(alpha))
                    )
                    ** 2
                    * (self.alpha[2] - alpha)
                    * np.cos(alpha)
                )
                / (
                    2
                    * E
                    * L
                    * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha)) ** 3
                )
                * engagement
            )

            Is0 = (
                ## primo termine
                (
                    1.2
                    * (1 + v)
                    * np.cos(alpha1) ** 2
                    * (
                        np.cos(alpha[2])
                        - (
                            (self.teethNumber - 2.5)
                            / (self.teethNumber * np.cos(self.pressureAngle))
                        )
                        * np.cos(alpha[3])
                    )
                )
                / (E * L * (np.sin(alpha[2])))
            )

            ## secondo termine

            Is = (
                (
                    1.2
                    * (1 + v)
                    * (self.alpha[2] - alpha)
                    * np.cos(alpha)
                    * np.cos(alpha1) ** 2
                )
                / (E * L * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha)))
                * engagement
            )

            Ia0 = (
                ## primo termine
                (
                    np.sin(alpha1) ** 2
                    * (
                        np.cos(
                            alpha[2]
                            - (
                                (self.teethNumber - 2.5)
                                / (self.teethNumber * np.cos(self.pressureAngle))
                            )
                            * np.cos(alpha[3])
                        )
                    )
                )
                / (2 * E * L * (np.sin(alpha[2])))
            )

            ## secondo termine

            Ia = (
                ((self.alpha[2] - alpha) * np.cos(alpha) * np.sin(alpha1) ** 2)
                / (
                    2
                    * E
                    * L
                    * (np.sin(alpha) + (self.alpha[2] - alpha) * np.cos(alpha))
                )
                * engagement
            )

        # Integrate over alfa
        # Kb_inv = np.sum(sc.integrate.trapezoid(Ib, x=alpha, axis=0))
        # Ks_inv = np.sum(sc.integrate.trapezoid(Is, x=alpha, axis=0))
        # Ka_inv = np.sum(sc.integrate.trapezoid(Ia, x=alpha, axis=0))

        # if self.root_greater_than_base:
        #     kb_inv += Ib0
        #     ks_inv += Is0
        #     ka_inv += Ia0

        # # Total stiffness
        # Kt = 1 / (Kb_inv + Ks_inv + Ka_inv)
        # if all(engagement == 0):
        #     print("No engagement detected.")
        # return Kt

    def exampleMeshDamping(self, t, x): ### fix
        return 0.005 + 0.002 * np.sin(t)

    


