# Generated by Luca Bernini and Daniele Raimondi on 25/02/2024

from progetto_gearbox.interfaces.simulation_interfaces import Model
from progetto_gearbox.enums.simulation_enums import SimulationMethod
from scipy.integrate import solve_ivp
import numpy as np
from bokeh.plotting import figure, output_file, show
from bokeh.models import Div
from bokeh.layouts import gridplot, column


class Simulation:
    simulation_number = 0

    def __init__(
        self,
        t_tot: float,
        deltat: float,
        model: Model,
        method: SimulationMethod = SimulationMethod.RK45,
    ):
        self.name = model.name + "_simulation"
        self.t_tot = t_tot
        self.deltat = deltat
        self.model = model
        self.initial_conditions = model.initial_conditions
        self.method = method

    def solve(self):
        solution = solve_ivp(
            self.model.process_equation,
            t_span=(0, self.t_tot),
            y0=self.initial_conditions,
            t_eval=np.arange(0, self.t_tot, self.deltat),
            method=self.method,
            # vectorized=True,
        )
        self.solution = {
            "time": solution.t,
            "states": solution.y,
            "inputs": self.model.get_inputs(solution.t),
            "outputs": self.model.get_outputs(solution.t, solution.y),
        }

    def states_plot(self, grids: list, shared_x_range):
        grids.append(
            Div(text=f"<h2>STATE PLOTS</h2>"),
        )
        for state_idx, (state, state_uom) in enumerate(
            zip(self.model.state_names, self.model.state_uoms)
        ):
            kwargs = dict(
                title=f"State {state.capitalize()}",
                x_axis_label="Time [s]",
                y_axis_label=f"{state.capitalize()} [{state_uom}]",
                width=400,
                height=300,
            )

            if shared_x_range is not None:
                kwargs["x_range"] = shared_x_range

            p = figure(**kwargs)

            if shared_x_range is None:
                shared_x_range = p.x_range

            p.line(x=self.solution["time"], y=self.solution["states"][state_idx, :])

            self.plots["states"].append(p)
        grids.append(gridplot(self.plots["states"], ncols=2))
        return grids, shared_x_range

    def inputs_plot(self, grids: list, shared_x_range):
        grids.append(
            Div(text=f"<h2>INPUT PLOTS</h2>"),
        )
        for input_idx, (input_name, input_uom) in enumerate(
            zip(self.model.input_names, self.model.input_uoms)
        ):
            kwargs = dict(
                title=f"Input {input_name.capitalize()}",
                x_axis_label="Time [s]",
                y_axis_label=f"{input_name.capitalize()} [{input_uom}]",
                width=400,
                height=300,
            )

            if shared_x_range is not None:
                kwargs["x_range"] = shared_x_range

            p = figure(**kwargs)

            if shared_x_range is None:
                shared_x_range = p.x_range

            p.line(x=self.solution["time"], y=self.solution["inputs"][input_idx, :])

            self.plots["inputs"].append(p)
        grids.append(gridplot(self.plots["inputs"], ncols=2))
        return grids, shared_x_range

    def outputs_plot(self, grids: list, shared_x_range):
        grids.append(
            Div(text=f"<h2>OUTPUT PLOTS</h2>"),
        )
        for output_idx, (output, output_uom) in enumerate(
            zip(self.model.output_names, self.model.output_uoms)
        ):
            kwargs = dict(
                title=f"Output {output.capitalize()}",
                x_axis_label="Time [s]",
                y_axis_label=f"{output.capitalize()} [{output_uom}]",
                width=400,
                height=300,
            )

            if shared_x_range is not None:
                kwargs["x_range"] = shared_x_range

            p = figure(**kwargs)

            if shared_x_range is None:
                shared_x_range = p.x_range

            p.line(x=self.solution["time"], y=self.solution["outputs"][output_idx, :])

            self.plots["outputs"].append(p)
        grids.append(gridplot(self.plots["outputs"], ncols=2))
        return grids, shared_x_range

    def plot(self):
        self.plots: dict[str, list[figure]] = {
            "states": [],
            "inputs": [],
            "outputs": [],
        }
        output_file(f"plots/{self.name}_plots.html")
        shared_x_range = None
        grids = []
        grids, shared_x_range = self.states_plot(grids, shared_x_range)
        grids, shared_x_range = self.inputs_plot(grids, shared_x_range)
        grids, shared_x_range = self.outputs_plot(grids, shared_x_range)
        layout = column(*grids)
        show(layout)
